extends PlayerParameters




const ATTACK_BOUNCE_POW = 8.0

const DAMAGE_THRESHOLD_BALL = 1
const DAMAGE_THRESHOLD_STRIKEDASH = 1
const DAMAGE_THRESHOLD_NORMAL = 0

const IDLE_MAX_SPEED = 0.1

const WALK_MAX_SPEED = 8.0
const WALK_SPEED_POWER = 3.0
const WALK_ANIM_SPEED_MOD = 1.0

const RUN_MAX_SPEED = 16.0
const RUN_SPEED_POWER = 3.0
const RUN_ANIM_SPEED_MOD = 0.5

const SPRINT_MAX_SPEED = 25.0
const SPRINT_ANIM_SPEED_MOD = 1.0

const SKID_MIN_STICK_MAGNITUDE = 0.6
const SKID_MAX_ANGLE = -0.75

const TEETER_MAX_SPEED = 3.0

const BALL_MIN_SPEED = 1.0

const AIR_INPUT_VEL = 2.0
const AIR_WATER_INPUT_VEL = 1.0

const JUMP_POWER = 10.0
